# golangci-lint configuration for tvclipboard project
# https://golangci-lint.run/usage/configuration/
version: 2

linters:
  disable:
    - errcheck

  enable:
    - govet
    - staticcheck
    - unused

  settings:
    staticcheck:
      checks:
        - all
        - '-QF1001'
        - '-ST1000'

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Exclude by default generated code
  exclude-use-default: false

  # Show only new issues
  new: false

  # Fix found issues (if it's supported by the linter)
  fix: false
